name: news_impact
description: A Flutter app for visualizing news trends and performing sentiment analysis.

dependencies:  
flutter:    
    sdk: flutter  
  http: ^0.14.0  
  provider: ^6.0.0  
  charts_flutter: ^0.12.0  
  flutter_local_notifications: ^12.0.4
  
dev_dependencies:  
flutter_test:    
  sdk: flutter  
flutter_lints: ^2.0.0

flutter:  
  assets:
      - assets/images/logo.png
        fonts:
            - family: CustomFont
                  fonts:
                          - asset: assets/fonts/custom_font.ttf